code --install-extension adpyke.vscode-sql-formatter
code --install-extension adrianwilczynski.alpine-js-intellisense
code --install-extension aliariff.auto-add-brackets
code --install-extension antfu.iconify
code --install-extension Asuka.insertnumbers
code --install-extension bastienboutonnet.vscode-dbt
code --install-extension bibhasdn.unique-lines
code --install-extension bierner.lit-html
code --install-extension bmalehorn.vscode-fish
code --install-extension bradlc.vscode-tailwindcss
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension brunnerh.insert-unicode
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension chunsen.bracket-select
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension damonsk.vscode-wardley-maps
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension EditorConfig.EditorConfig
code --install-extension ElecTreeFrying.insert-random-text
code --install-extension hbenl.vscode-test-explorer
code --install-extension henriblancke.vscode-dbt-formatter
code --install-extension KevinRose.vsc-python-indent
code --install-extension leodevbro.blockman
code --install-extension lokalise.i18n-ally
code --install-extension ms-python.black-formatter
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.test-adapter-converter
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension ritwickdey.LiveServer
code --install-extension rlivings39.fzf-quick-open
code --install-extension samuelcolvin.jinjahtml
code --install-extension skyapps.fish-vscode
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tushortz.python-extended-snippets
code --install-extension Tyriar.sort-lines
code --install-extension usernamehw.errorlens
