sleepy_run.py --action signal -- python -u -m xklb.lb dl --image --photos /home/xk/lb/fs/61_Photos_Unsorted.db --prefix /home/xk/d/61_Photos_Unsorted/gallery-dl/ -L 777 -w 'm.path like "https://i.imgur%"' -w 'lower(m.path) != m.path' $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --image --photos ~/lb/fs/91_New_Art.db --image --photos --prefix /mnt/d/91_New_Art/ -L 777 -w 'm.path like "%imgur%"' -w 'lower(m.path) != m.path' $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --image --photos ~/lb/fs/91_New_Art.db --image --photos --prefix /mnt/d/91_New_Art/ -L 777 -w 'm.path like "%reddit.com%"' -w 'lower(m.path) != m.path' $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --audio ~/lb/audio.db --prefix /mnt/d/81_New_Music/ -w 'm.path like "%soundcloud%"' -w 'lower(m.path) != m.path' $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --audio ~/lb/audio.db --prefix /mnt/d/81_New_Music/ -L 777 -w 'lower(m.path) != m.path' 'm.path not like "%imgur%"' 'm.path not like "%redd.it%"' 'm.path not like "%reddit.com%"' -u "ROW_NUMBER() OVER ( PARTITION BY SUBSTR(m.path, INSTR(m.path, '//') + 2, INSTR( SUBSTR(m.path, INSTR(m.path, '//') + 2), '/') - 1) ), random" -i $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --video --small ~/lb/fs/tax.db --prefix /mnt/d/69_Taxes/ -L 777 -w 'lower(m.path) != m.path' 'm.path not like "%imgur%"' 'm.path not like "%redd.it%"' 'm.path not like "%reddit.com%"' -u "ROW_NUMBER() OVER ( PARTITION BY SUBSTR(m.path, INSTR(m.path, '//') + 2, INSTR( SUBSTR(m.path, INSTR(m.path, '//') + 2), '/') - 1) ), random" -i $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --video --small ~/lb/video.db --prefix /mnt/d/71_Mealtime_Videos/ -L 777 -w 'lower(m.path) != m.path' 'm.path not like "%imgur%"' 'm.path not like "%redd.it%"' 'm.path not like "%reddit.com%"' -u "ROW_NUMBER() OVER ( PARTITION BY SUBSTR(m.path, INSTR(m.path, '//') + 2, INSTR( SUBSTR(m.path, INSTR(m.path, '//') + 2), '/') - 1) ), random" -i $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --image --photos /home/xk/lb/fs/61_Photos_Unsorted.db --prefix /home/xk/d/61_Photos_Unsorted/gallery-dl/ -L 777 -w 'm.path like "%i.redd.it%jpg"' $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --image --photos /home/xk/lb/fs/61_Photos_Unsorted.db --prefix /home/xk/d/61_Photos_Unsorted/gallery-dl/ -L 777 -w 'm.path not like "%imgur%"' 'm.path not like "%redd.it%"' 'm.path not like "%reddit.com%"' -u 'random()' -u "ROW_NUMBER() OVER ( PARTITION BY SUBSTR(m.path, INSTR(m.path, '//') + 2, INSTR( SUBSTR(m.path, INSTR(m.path, '//') + 2), '/') - 1) ), random" -i $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --image --photos /home/xk/lb/fs/61_Photos_Unsorted.db --prefix /home/xk/d/61_Photos_Unsorted/gallery-dl/ -L 777 -w 'm.path not like "%imgur%"' 'm.path not like "%redd.it%"' 'm.path not like "%reddit.com%"' -i $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --image --photos /home/xk/lb/fs/61_Photos_Unsorted.db --prefix /home/xk/d/61_Photos_Unsorted/gallery-dl/ -L 777 -w 'm.path like "%m.imgur%"' $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --image --photos ~/lb/fs/91_New_Art.db --image --photos --prefix /mnt/d/91_New_Art/ -L 777 -w 'm.path like "%redd.it%"' $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --image --photos /home/xk/lb/fs/61_Photos_Unsorted.db --prefix /home/xk/d/61_Photos_Unsorted/gallery-dl/ -L 777 -w 'm.path like "https://i.imgur%"' $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --image --photos ~/lb/fs/61_Photos_Unsorted.db --prefix ~/d/61_Photos_Unsorted/gallery-dl/ -L 777 -w 'm.path not like "%imgur%"' 'm.path not like "%redd.it%"' 'm.path not like "%reddit.com%"' -u "ROW_NUMBER() OVER ( PARTITION BY SUBSTR(m.path, INSTR(m.path, '//') + 2, INSTR( SUBSTR(m.path, INSTR(m.path, '//') + 2), '/') - 1) ), random" -i $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --image --photos ~/lb/fs/91_New_Art.db --image --photos --prefix /mnt/d/91_New_Art/ -L 777 -w 'm.path like "%imgur%"' $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --image --photos ~/lb/fs/91_New_Art.db --image --photos --prefix /mnt/d/91_New_Art/ -L 777 -w 'm.path like "%reddit.com%"' $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --audio ~/lb/audio.db --prefix /mnt/d/81_New_Music/ -w 'm.path like "%soundcloud%"' $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --audio ~/lb/audio.db --prefix /mnt/d/81_New_Music/ -L 777 -w 'm.path not like "%imgur%"' 'm.path not like "%redd.it%"' 'm.path not like "%reddit.com%"' -u "ROW_NUMBER() OVER ( PARTITION BY SUBSTR(m.path, INSTR(m.path, '//') + 2, INSTR( SUBSTR(m.path, INSTR(m.path, '//') + 2), '/') - 1) ), random" -i $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --video --small ~/lb/fs/tax.db --prefix /mnt/d/69_Taxes/ -L 777 -w 'm.path not like "%imgur%"' 'm.path not like "%redd.it%"' 'm.path not like "%reddit.com%"' -u "ROW_NUMBER() OVER ( PARTITION BY SUBSTR(m.path, INSTR(m.path, '//') + 2, INSTR( SUBSTR(m.path, INSTR(m.path, '//') + 2), '/') - 1) ), random" -i $argv
sleepy_run.py --action signal -- python -u -m xklb.lb dl --video --small ~/lb/video.db --prefix /mnt/d/71_Mealtime_Videos/ -L 777 -w 'm.path not like "%imgur%"' 'm.path not like "%redd.it%"' 'm.path not like "%reddit.com%"' -u "ROW_NUMBER() OVER ( PARTITION BY SUBSTR(m.path, INSTR(m.path, '//') + 2, INSTR( SUBSTR(m.path, INSTR(m.path, '//') + 2), '/') - 1) ), random" -i $argv
