# Defined in /home/xk/.config/fish/functions/goformat.fish @ line 2, copied in /home/xk/.config/fish/functions/funccp.fish @ line 3
function goformat.all
    staticcheck $argv ./...
    go vet -c=1 $argv ./...
    gofmt -s -w -e .
    go fix $argv ./...
    goimports -w -e .
    gofumpt -w .
    gci write .
    golangci-lint run --build-tags fts5 --fix ./...
end
