context.modules = [
{   name = libpipewire-module-combine-stream
    args = {
        combine.mode = sink
        node.name = "surround_sink"
        node.description = "Surround Sound"
        combine.latency-compensate = true
        combine.props = {
            audio.position = [ FL FR ]
        }
        stream.props = {
        }
        stream.rules = [
            # 1. USB Apple Dongle: Flipped Stereo (Front Right on Left, Front Left on Right)
            {
                matches = [
                    {
                        media.class = "Audio/Sink"
                        node.name = "alsa_output.usb-Apple__Inc._USB-C_to_3.5mm_Headphone_Jack_Adapter_DWH152405TPJKLTA5-00.analog-stereo"
                    }
                ]
                actions = {
                    create-stream = {
                        combine.audio.position = [ FL FR ]
                        audio.position = [ FR FL ]

                        stream.props = {
                            # Delay expressed in samples / sample_rate (e.g., 2400 / 48000 = 50ms)
                            node.latency = "960/48000"
                        }
                    }
                }
            }
            # 2. HDMI Output: Normal Stereo
            {
                matches = [
                    {
                        media.class = "Audio/Sink"
                        node.name = "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra3"
                    }
                ]
                actions = {
                    create-stream = {
                        combine.audio.position = [ FL FR ]
                        audio.position = [ FL FR ]
                    }
                }
            }
        ]
    }
}
]
