[General]
FullscreenOnStartup=true
MenuOnStartup=false
MouseHideOnTimeout=2
PlaylistFile=/home/xk/.projectM/playlist
playlistDockLocation=2
playlistDocked=true
playlistPath=/home/xk/.projectM
playlistPos=@Point(0 0)
playlistWindowSize=@Size(315 111)
pos=@Point(0 0)
